---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: zooros
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    #  - rustup
    #  - erlang
    #  - erlang-rebar3
    #  - elixir
      
    #remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      #- firefox
      #- firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case) 

  - type: brew
    brew-analytics: false
    nofile-limits: true
    
  - type: script
    snippets:
      - "brew install rustup"
      - "brew install erlang"
      - "brew install rebar3"
      - "brew install elixir"
      - "brew install gleam"
      - "brew install go"
      - "brew install yazi"
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.gnome.Loupe
        - com.vivaldi.Vivaldi
        - com.github.Murmele.Gittyup
        - com.visualstudio.code
        - org.racket_lang.Racket
        - com.valvesoftware.Steam
      remove:
        - org.gnome.eog
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

